### PR TITLE
Impl/order history expo

### PR DESCRIPTION
**Pull request by Sergemuhundu**
-   [x] Have you followed the [contributing guidelines](https://github.com/ever-co/ever/blob/master/.github/CONTRIBUTING.md)?
-   [x] Have you explained what your changes do, and why they add value?

**Please note: we will close your PR without comment if you do not check the box

How it looks now

WhatsApp Image 2022-07-23 at 05 24 15 (1)
es above and provide ALL requested information.**

---

### CODE REVIEW

**Comment by evereq** [comment]
@Sergemuhundu , please click the button "CLA | not signed yet" (https://github.com/ever-co/ever-demand/pull/1506#issuecomment-1193366581)  and follow the requirements of it to sign the CAA document.

**Comment by Neosoulink** [comment]
LGTM

**Comment by Neosoulink** [comment]
**❗❗ @Sergemuhundu, 
I don't think we can merge these codes, you took the codes from another branch intended for the implementation of the Flutter clone**

**Comment by Neosoulink** [comment]
> **❗❗ @Sergemuhundu, I don't think we can merge these codes, you took the codes from another branch intended for the implementation of the Flutter clone**

You have to create a branch from this feature branch

**Comment by Neosoulink** [comment]
There are too many changes that you didn't implement that end up in this PR;

Try to create another branch from[feature/shop-mobile-expoV0.4.3](https://github.com/ever-co/ever-demand/tree/feature/shop-mobile-expoV0.4.3) et nome la `impl/feature/shop-mobile-expoV0.4.3@orderHistory`.

I close this PR

**Pull request closed without merging**
